#!/bin/bash

# Set font information
xset +fp /usr/share/fonts/local
xset +fp /usr/share/fonts/misc
xset +fp $HOME/.fonts
xset fp rehash

xsetroot -cursor_name left_ptr
xrdb -merge ~/.Xresources

# Let bspwm handle starting other daemons.
exec bspwm
