#!/bin/bash
xset +fp /usr/share/fonts/local
xset +fp /usr/share/fonts/misc
xset +fp $HOME/.fonts
xset fp rehash

xsetroot -cursor_name left_ptr
xrdb -merge ~/.Xresources

export PATH="~/.bin:${PATH}"

exec bspwm
