#! /bin/sh
xmodmap ~/.xmodmaprc &

bspc config top_padding 24px
bspc config border_width           4
bspc config normal_border_color   "#69b2d6" #blue
bspc config presel_border_color   "#69e1d3" #cyan
bspc config focused_border_color  "#89d2f6" #"#db7464" #red
bspc config window_gap             10
bspc config split_ratio            0.56
bspc config borderless_monocle     true
bspc config gapless_monocle        true

bspc monitor -d browser terminal dev remote trash

wmname LG3D &

dunst &
sxhkd &
compton &
tint3 &
