#! /bin/sh
xmodmap ~/.xmodmaprc &

~/.config/bspwm/gruvbox

export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'

wmname LG3D &
dunst &
sxhkd &
compton &
tint3 &

