#!/bin/bash
feh --bg-scale /home/ted/.rwpcd/nice/castle.jpg
#bspc rule -a "*" floating=on
bspc config top_padding            26
bspc config focus_by_distance   true
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.9
bspc config focus_follows_pointer true

bspc config border_width           0
bspc config normal_border_color   "#aaaaaa"
bspc config focused_border_color  "#ffffff"

bspc monitor -d inet term sshs devl rand
