#!/bin/bash

PROMPT_COMMAND=precmd
precmd() {
  GIT=""
  LOC="${PWD/$HOME/\~}"

  if [ -f ~/.bash/git.sh ]; then
    GIT=$(~/.bash/git.sh)
  fi

  if [ -f ./.shortpath ]; then
    LOC=$(basename $PWD)
  fi

  if [ "$DISPLAY" ]; then
    if [ "$(which psg2)" ]; then
      if [ -f ~/.config/psg/psg.json ]; then
        export PS1="$(cat ~/.config/psg/psg.json | psg2 user=$USER path="$LOC" git="$GIT")"
        return
      fi
    fi
  fi

  export PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
}
