#! /bin/sh

# Hightlight window under the mouse at all times.
bspc config focus_follows_pointer true

# Use the super key to resize and move windows.
# bspc config pointer_modifier mod4

# Use left mouse to move windows.
# bspc config pointer_action1 move

# Use middle mouse for resizing only edges.
# bspc config pointer_action2 resize_side

# use right mouse to resize freely.
# bspc config pointer_action3 resize_corner

# borders
bspc config border_width 3
bspc config window_gap 8
bspc config normal_border_color "#000000"
bspc config active_border_color "#000000"
bspc config focused_border_color "#126612"
bspc config presel_feedback_color "#121266"

# default borders and splits
bspc config split_ratio            0.50
bspc config borderless_monocle     true
bspc config gapless_monocle        true

# Run post bspwm start
$HOME/.config/x11/post_wm.sh &
