# don't mess around in the login shell land
case $- in
    *i*) ;;
      *) return;;
esac


# Alias definitions.
if [ -e ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi


# set bash variables
HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000
shopt -s checkwinsize
shopt -s histappend


# Set path variables
export PATH="$HOME/.xbin/:$HOME/.bin:$PATH"


# Enable bash_completion
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi


# Allow for per-host bashrc customization
if [ -e ~/.bash/set_ps1 ]; then
    . ~/.bash/set_ps1
fi


# Vim support
if [ -e ~/.bash/vim_integration ]; then
    . ~/.bash/vim_integration
fi


# Golang support
if [ -e ~/.bash/golang_support ]; then
    . ~/.bash/golang_support
fi


# change directory colors
eval $(dircolors -b)
