load("//dotfiles/target_definitions.py")

ConfigSet (
  name = "bash_config",
  deps = [ "//dotfiles:impulse_binary" ],
  files = [
    ("bash_aliases", "{HOME}/.bash_aliases"),
    ("bash_profile", "{HOME}/.bash_profile"),
    ("bashrc", "{HOME}/.bashrc"),
  ],
)