#!/bin/bash

# Set up the fonts
# xset +fp /usr/share/fonts/local
# xset +fp /usr/share/fonts/misc
# xset +fp $HOME/.fonts
xset fp rehash

# Always set the cursor to the normal cursor
xsetroot -cursor_name left_ptr

# Can do things like disable caps lock
xmodmap ~/.xmodmaprc

# merge and include any resources
xrdb -merge ~/.Xresources

# Run pre-WM scripts
exec ~/.config/x11/pre_wm.sh &

# Start the window manager
exec ~/.config/x11/start_wm.sh
